<?php
// Load environment variables
require __DIR__ . '/../vendor/autoload.php';
$dotenv = Dotenv\Dotenv::createImmutable(__DIR__ . '/..');
$dotenv->load();
// Test Google OAuth credentials
define('GOOGLE_CLIENT_ID', $_ENV['GOOGLE_CLIENT_ID']);
define('GOOGLE_CLIENT_SECRET', $_ENV['GOOGLE_CLIENT_SECRET']);
define('GOOGLE_REDIRECT_URI', $_ENV['CALLBACK_URL']);
echo "<h1>🔍 Google OAuth Credentials Test</h1>";
echo "<div style='background: #f8f9fa; padding: 15px; margin: 10px 0; border-radius: 5px;'>";
echo "<h3>📋 Configuration Check:</h3>";
echo "<ul>";
echo "<li><strong>Client ID:</strong> " . htmlspecialchars(GOOGLE_CLIENT_ID) . "</li>";
echo "<li><strong>Client Secret:</strong> " . substr(GOOGLE_CLIENT_SECRET, 0, 10) . "...</li>";
echo "<li><strong>Redirect URI:</strong> " . htmlspecialchars(GOOGLE_REDIRECT_URI) . "</li>";
echo "</ul>";
echo "</div>";
echo "<div style='background: #e2e3e5; padding: 15px; margin: 10px 0; border-radius: 5px;'>";
echo "<h3>🔗 Test URLs:</h3>";
echo "<p><strong>OAuth Authorization URL:</strong></p>";
echo "<a href='https://accounts.google.com/o/oauth2/auth?client_id=" . GOOGLE_CLIENT_ID . "&redirect_uri=" . urlencode(GOOGLE_REDIRECT_URI) . "&scope=https://www.googleapis.com/auth/youtube.readonly&response_type=code&access_type=offline&prompt=consent&state=test' target='_blank' style='background: #4285f4; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px;'>🔗 Test OAuth Flow</a>";
echo "<p style='margin-top: 15px;'><strong>Manual Test URL:</strong></p>";
echo "<code style='background: #f8f9fa; padding: 5px; border-radius: 3px; display: block;'>https://accounts.google.com/o/oauth2/auth?client_id=" . GOOGLE_CLIENT_ID . "&redirect_uri=" . urlencode(GOOGLE_REDIRECT_URI) . "&scope=https://www.googleapis.com/auth/youtube.readonly&response_type=code&access_type=offline&prompt=consent&state=debug-callback.php</code>";
echo "</div>";
echo "<div style='background: #fff3cd; padding: 15px; margin: 10px 0; border-radius: 5px;'>";
echo "<h3>🛠️  What to check in Google Console:</h3>";
echo "<ol>";
echo "<li><strong>Authorized redirect URI:</strong> Must be exactly <code>" . GOOGLE_REDIRECT_URI . "</code></li>";
echo "<li><strong>Authorized JavaScript origin:</strong> Must include <code>https://housemadeeasy.com.ng</code></li>";
echo "<li><strong>OAuth consent screen:</strong> Must be configured and approved</li>";
echo "<li><strong>YouTube Data API:</strong> Must be enabled in your project</li>";
echo "</ol>";
echo "</div>";
echo "<div style='background: #d1ecf1; padding: 15px; margin: 10px 0; border-radius: 5px;'>";
echo "<h3>🔍 Debug Steps:</h3>";
echo "<ol>";
echo "<li>Click the test URL above</li>";
echo "<li>Complete Google OAuth (use same Google account as console)</li>";
echo "<li>Check <code>debug-callback.php</code> to see the detailed token exchange</li>";
echo "<li>If still failing, the issue is likely redirect URI mismatch</li>";
echo "</ol>";
echo "</div>";
echo "<div style='background: #f8d7da; padding: 15px; margin: 10px 0; border-radius: 5px;'>";
echo "<h3>⚠️  Common Issues:</h3>";
echo "<ul>";
echo "<li><strong>Redirect URI mismatch:</strong> Google console vs actual URL must match exactly</li>";
echo "<li><strong>Project not published:</strong> OAuth consent screen must be in production</li>";
echo "<li><strong>Scope not approved:</strong> YouTube scopes need verification</li>";
echo "<li><strong>Wrong Google account:</strong> Use the same account as the console</li>";
echo "</ul>";
echo "</div>";
?>
